# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Takuzu' do
  rn_path = '../node_modules/react-native'
  platform :ios, '9.0'
  # Very IMPORTANT to have, unless you removed React dependencies for Libraries 
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      # 'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end